baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Euruko 2020"
baseURL = "https://euruko2020.org/"

disableHugoGeneratorInject = true

enableRobotsTXT = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "Calendar"]

[params]
  description = "Euruko 2020 will be held on the 21st and 22nd of August at the Savoy Theatre"
  twitter_card = "images/twitter-card.png"
  facebook_share = "images/facebook-share.png"
