name: Build (and deploy)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.64.0'
    - name: Install dependencies with Yarn
      run: yarn install
    - name: Build site
      run: yarn build
    - name: Upload build
      uses: actions/upload-artifact@master
      with:
        name: site-build-${{github.sha}}
        path: dist

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/download-artifact@master
  #     with:
  #       name: site-build-${{github.sha}}
  #       path: dist/
  #   - run: ls -lh dist/
  #   - run: echo ${{github.ref}}
  #   - name: Deploy
  #     uses: peaceiris/actions-gh-pages@v2
  #     env:
  #       ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
  #       EXTERNAL_REPOSITORY: euruko/euruko2020.github.io
  #       PUBLISH_BRANCH: gh-pages
  #       PUBLISH_DIR: ./dist
  #     if: github.ref == 'refs/heads/master' && success()
