name: Build site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.64.0'
    - name: Install Yarn
      run: npm install -g yarn@berry
    - name: Install dependencies with Yarn
      run: yarn install
    - name: Build site
      run: yarn build
